# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
20.times do |n|
  Event.create(title: "イベント#{n+1}",start_datetime: "2019-11-#{n+1} #{n+1}:00:00",end_datetime: "2019-11-#{n+1} #{n+4}:00:00", prefecture:"大阪府")
  Event.create(title: "勉強会#{n+1}",start_datetime: "2019-11-#{n+1} #{n+1}:00:00",end_datetime: "2019-11-#{n+1} #{n+4}:00:00",prefecture:"東京都")
end
20.times do |n|
  Event.create(title: "イベント#{n+21}",start_datetime: "2019-11-#{n+1} #{n+1}:00:00",end_datetime: "2019-11-#{n+1} #{n+4}:00:00", prefecture:"神奈川県")
  Event.create(title: "勉強会#{n+21}",start_datetime: "2019-11-#{n+1} #{n+1}:00:00",end_datetime: "2019-11-#{n+1} #{n+4}:00:00",prefecture:"愛知県")
end

# ＜都道府県＞
# Event.create!(prefecture: "北海道")
# Event.create!(prefecture:"青森県")
# Event.create!(prefecture:"岩手県")
# Event.create!(prefecture:"宮城県")
# Event.create!(prefecture:"秋田県")
# Event.create!(prefecture:"山形県")
# Event.create!(prefecture:"福島県")
# Event.create!(prefecture:"茨城県")
# Event.create!(prefecture:"栃木県")
# Event.create!(prefecture:"群馬県")
# Event.create!(prefecture:"埼玉県")
# Event.create!(prefecture:"千葉県")
# Event.create!(prefecture:"東京都")
# Event.create!(prefecture:"神奈川県")
# Event.create!(prefecture:"新潟県")
# Event.create!(prefecture:"富山県")
# Event.create!(prefecture:"石川県")
# Event.create!(prefecture:"福井県")
# Event.create!(prefecture:"山梨県")
# Event.create!(prefecture:"長野県")
# Event.create!(prefecture:"岐阜県")
# Event.create!(prefecture:"静岡県")
# Event.create!(prefecture:"愛知県")
# Event.create!(prefecture:"三重県")
# Event.create!(prefecture:"滋賀県")
# Event.create!(prefecture:"京都府")
# Event.create!(prefecture:"大阪府")
# Event.create!(prefecture:"兵庫県")
# Event.create!(prefecture:"奈良県")
# Event.create!(prefecture:"和歌山県")
# Event.create!(prefecture:"鳥取県")
# Event.create!(prefecture:"島根県")
# Event.create!(prefecture:"岡山県")
# Event.create!(prefecture:"広島県")
# Event.create!(prefecture:"山口県")
# Event.create!(prefecture:"徳島県")
# Event.create!(prefecture:"香川県")
# Event.create!(prefecture:"愛媛県")
# Event.create!(prefecture:"高知県")
# Event.create!(prefecture:"福岡県")
# Event.create!(prefecture:"佐賀県")
# Event.create!(prefecture:"長崎県")
# Event.create!(prefecture:"熊本県")
# Event.create!(prefecture:"大分県")
# Event.create!(prefecture:"宮崎県")
# Event.create!(prefecture:"鹿児島県")
# Event.create!(prefecture:"沖縄県")
